name: opensource-hyde
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10.13
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pip
  - pip:
    - transformers
    - datasets
    - huggingface-hub
    - tqdm
    - requests
    - protobuf
    - faiss-cpu
    - pyserini
    - openai
    - cohere
